FORMAT: 1A
HOST: http://api-inpocket.herokuapp.com/

# inPocket API

## Device authentication [/v1/devices/authenticate]

### POST [POST]
Action for device authentication after first application boot.

+ Attributes
    + platform  (enum[string], required)

      + Members
          + `ios`
          + `android`
          + `web`
    + push_token (string, required) - specific token for push notifications
  
+ Request (application/json)

        {
            "platform": "ios",
            "push_token": "ce8be627 2e43e855 16033e24 b4c28922 0eeda487 9c477160 b2545e95 b68b5969"
        }

+ Response 200 (application/json)

        {
            "device": {
            "access_token": "TaEKW9UCQLnRdhQsXqoNsvEP"
            },
            "user": {
                "id": 41,
                "first_name": null,
                "last_name": null,
                "photo": null
            }
        }

## Place [/v1/places/{id}]

+ Parameters
    + id (number)

+ Model (application/json)

    JSON representation of place.

    + Body
    
            {
                "id": 2,
                "description": "Идея популяризации домашней итальянской кухни пришла к нам из Германии, где и появилось первое кафе всемирно известной сети Vapiano в 2002 году. Открывая заведения сети в Москве, мы постарались донести до столичных гурманов основополагающую концепцию Vapiano в первоначальном виде.",
                "name": "Vapiano",
                "address": "Червоноармiйська-Бассейна 1-3/2 Киев",
                "phones": [],
                "logo": "http://www.downtowndc.org/sites/default/files/images/poi/Vapiano%20Logo.jpg",
                "images": [],
                "lng": "30.5234",
                "lat": "50.4501"
            }

### GET
+ Response 200

    [Place][]

## Places Collection [/v1/places]

+ Model (application/json)

    JSON representation of places.

    + Body
    
            [{
                "id": 2,
                "description": "Идея популяризации домашней итальянской кухни пришла к нам из Германии, где и появилось первое кафе всемирно известной сети Vapiano в 2002 году. Открывая заведения сети в Москве, мы постарались донести до столичных гурманов основополагающую концепцию Vapiano в первоначальном виде.",
                "name": "Vapiano",
                "address": "Червоноармiйська-Бассейна 1-3/2 Киев",
                "phones": [],
                "logo": "http://www.downtowndc.org/sites/default/files/images/poi/Vapiano%20Logo.jpg",
                "images": [],
                "lng": "30.5234",
                "lat": "50.4501"
            },
            {
                "id": 3,
                "description": "Идея популяризации домашней итальянской кухни пришла к нам из Германии, где и появилось первое кафе всемирно известной сети Vapiano в 2002 году. Открывая заведения сети в Москве, мы постарались донести до столичных гурманов основополагающую концепцию Vapiano в первоначальном виде.",
                "name": "Vapiano",
                "address": "Червоноармiйська-Бассейна 1-3/2 Kyiv",
                "phones": [],
                "logo": "http://www.downtowndc.org/sites/default/files/images/poi/Vapiano%20Logo.jpg",
                "images": [],
                "lng": "30.5234",
                "lat": "50.4501"
            }]

### GET

+ Response 200

    [Places Collection][]