version: '2'
services:
  db:
    image: postgres

  web:
    build: .
    command: bundle exec foreman start
    volumes:
      - .:/pocket_waiter
      - bundle:/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  bundle: {}

  # spring:
  #   build: .
  #   volumes:
  #     - .:/pocket_waiter
  #   command: spring server
  #
  #   # This ensures that the pid namespace is shared between the host
  #   # and the container. It's not necessary to be able to run spring
  #   # commands, but it is necessary for "spring status" and "spring stop"
  #   # to work properly.
  #   pid: host
